실습과제 1

In [ ]:
import numpy

In [ ]:
A = numpy.random.randint(1, 99, size=(2,8))

# A 벡터의 정보 출력
print(A.shape)
print(A.shape[0])
print(A.shape[1])
print(A)
#print(type(A))

(2, 8)
2
8
[[63 51 94 12 63 98 82  1]
 [98 43 84 57 20 44  5 68]]


In [ ]:
# A 벡터 전체 원소들의 최댓값과 서브 벡터 내의 최댓값 출력
for i in range(A.shape[0]):
    allMax = A[i][0]
    for j in range(1, A.shape[1]):
        if A[i][j] > allMax:
            allMax = A[i][j]
print("All Max: ", allMax)

for i in range(A.shape[0]):
    subMax = A[i][0]
    for j in range(1, A.shape[1]):
        if A[i][j] > subMax:
            subMax = A[i][j]
    print("SubMax", i, ": ", subMax)

All Max:  93
SubMax 0 :  89
SubMax 1 :  93


In [ ]:
# 2차원 벡터 A를 3차원 벡터 B로 변환
B = A.reshape(2, 2, 4)
print(B.shape)
print(B)

(2, 2, 4)
[[[ 1 54 19 19]
  [89 63 21 67]]

 [[66 72 34 81]
  [ 5 34 78 93]]]


실습과제2

In [ ]:
# 슬라이싱 기능을 사용해 벡터 C 저장, 출력
C = B.copy()
#print(C)
C[:,:,0:2] = B[:,:,2:]
C[:,:,2:] = B[:,:,:2]
print(C)

[[[19 19  1 54]
  [21 67 89 63]]

 [[34 81 66 72]
  [78 93  5 34]]]
